const bcrypt = require('bcrypt');
const supabase = require('../utils/dbConnection');
const { signToken } = require('../utils/jwt');


// ============================
// 🏢 SIGNUP COMPANY
// ============================
exports.signupCompany = async (req, res) => {
  try {
    const { company_name, email, password, phone, logo_path } = req.body;

    // check email exists
    const { data: existing } = await supabase
      .from('company')
      .select('email')
      .eq('email', email)
      .maybeSingle();

    if (existing) {
      return res.status(400).json({ message: 'Email already exists' });
    }

    // hash password
    const password_hash = await bcrypt.hash(password, 10);

    // insert (company_id auto-generated by Supabase UUID)
    const { data, error } = await supabase
      .from('company')
      .insert([
        {
          company_name,
          email,
          password: password_hash,
          phone,
          logo_path: logo_path || null
        }
      ])
      .select()
      .single();

    if (error) {return res.status(400).json({ error: error.message });}
    
     // generate token
    const token = signToken({
      id: data.company_id,
      role: 'company'
    });

    res.status(201).json({
      message: 'Company created successfully',
      company: {
        company_id: data.company_id,
        company_name: data.company_name,
        email: data.email,
        phone: data.phone,
        logo_path: data.logo_path
      }
    });

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};


// ============================
// 🔐 LOGIN COMPANY
// ============================
exports.loginCompany = async (req, res) => {
  try {
    const { email, password } = req.body;

    const { data: company } = await supabase
      .from('company')
      .select('*')
      .eq('email', email)
      .maybeSingle();

    if (!company) {
      return res.status(400).json({ message: 'Invalid credentials' });
    }

    const isMatch = await bcrypt.compare(password, company.password);

    if (!isMatch) {
      return res.status(400).json({ message: 'Invalid credentials' });
    }

    const token = signToken({
      id: company.company_id,
      role: 'company'
    });

    res.json({
      message: 'Login successful',
      token,
      company: {
        company_id: company.company_id,
        company_name: company.company_name,
        email: company.email,
        phone: company.phone,
        logo_path: company.logo_path
      }
    });

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};


// ============================
// 👤 GET COMPANY PROFILE
// ============================
exports.getCompanyProfile = async (req, res) => {
  try {
    const companyId = req.user.id;

    const { data, error } = await supabase
      .from('company')
      .select('company_id, company_name, email, phone, logo_path, created_at')
      .eq('company_id', companyId)
      .single();

    if (error) return res.status(400).json({ error: error.message });

    res.json({ company: data });

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};